spring.application.name=biblioteca-api

# 1. La URL limpia (solo con el host y el nombre de la base de datos)
spring.datasource.url=jdbc:postgresql://://render.com

# 2. El usuario por separado
spring.datasource.username=biblioteca_44da_user

# 3. La contraseña por separado
spring.datasource.password=uKyDAdHnfTUHHj4whx2G2eqCsnpaxkW5

# Configuración del motor de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



