spring.application.name=biblioteca-api


spring.datasource.url=jdbc:postgresql://biblioteca_44da_user:uKyDAdHnfTUHHj4whx2G2eqCsnpaxkW5@dpg-d8hi00nlk1mc73ei6sb0-a/biblioteca_44da

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


